import type { Metadata } from 'next'
import '../styles/globals.css'
import { ApolloClientProvider } from '@/providers/apollo-client-provider'
import { NextIntlClientProvider } from 'next-intl'
import { getLocale, getMessages } from 'next-intl/server'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default async function RootLayout({ children }: LayoutProps<'/'>) {
	const locale = await getLocale()
	const messages = await getMessages()
	return (
		<html lang={locale}>
			<body>
				<ApolloClientProvider>
					<NextIntlClientProvider messages={messages}>
						{children}
					</NextIntlClientProvider>
				</ApolloClientProvider>
			</body>
		</html>
	)
}
