import type { Metadata } from 'next'
import '../styles/globals.css'
import { ApolloClientProvider } from '@/providers/apollo-client-provider'
import { NextIntlClientProvider } from 'next-intl'
import { getLocale, getMessages } from 'next-intl/server'
import { Geist } from 'next/font/google'
import { cn } from 'cn'
import { ThemeProvider } from '@/providers/theme-provider'

const geist = Geist({ subsets: ['latin'], variable: '--font-sans' })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default async function RootLayout({ children }: LayoutProps<'/'>) {
	const locale = await getLocale()
	const messages = await getMessages()
	return (
		<html
			lang={locale}
			className={cn('font-sans', geist.variable)}
			suppressHydrationWarning
		>
			<body>
				<ApolloClientProvider>
					<NextIntlClientProvider messages={messages}>
						<ThemeProvider
							attribute='class'
							defaultTheme='dark'
							disableTransitionOnChange
						>
							{children}
						</ThemeProvider>
					</NextIntlClientProvider>
				</ApolloClientProvider>
			</body>
		</html>
	)
}
